#!/usr/bin/env python3
"""T5: route reader-stop clusters + contradictions to the creator queue as proposals.

Read-only inputs:
  data/intel/duane_book/qa/literary_runs/2026*.json   (patch_* excluded)
  data/intel/duane_book/qa/chapter_briefs/ch*_regrade_run*.json
  data/intel/duane_book/qa/duane_review_queue.md      (read-only, never edited)
Writes:
  data/intel/duane_book/qa/creator_queue_proposals.md
Python 3 stdlib only.
"""
import glob
import json
import os
import re

QA = os.path.join("data", "intel", "duane_book", "qa")
OUT = os.path.join(QA, "creator_queue_proposals.md")
QUEUE = os.path.join(QA, "duane_review_queue.md")

THEMES = [
    ("side_income", re.compile(r"youtube|channel|side income|flow|advertis", re.I)),
    ("job_loss", re.compile(r"ageism|laid off|job|applications|feelers", re.I)),
    ("debt", re.compile(r"loan|borrow", re.I)),
]


def classify(text):
    for name, rx in THEMES:
        if rx.search(text):
            return name
    return "other"


def iter_reader_stops():
    """Yield (run_label, persona, chapter, quote) for every non-null stop_at."""
    for path in sorted(glob.glob(os.path.join(QA, "literary_runs", "2026*.json"))):
        if os.path.basename(path).startswith("patch_"):
            continue
        d = json.load(open(path))
        for k, v in d.get("raw", {}).items():
            m = re.match(r"reader\|(.+)$", k)
            if not m or not isinstance(v, dict):
                continue
            for ch, row in (v.get("chapters") or {}).items():
                q = row.get("stop_at")
                if q:
                    yield (os.path.basename(path), m.group(1), ch, q)
    for path in sorted(glob.glob(os.path.join(QA, "chapter_briefs", "ch*_regrade_run*.json"))):
        d = json.load(open(path))
        m = re.match(r"ch(\d+)_", os.path.basename(path))
        ch = m.group(1) if m else "?"
        for k, v in d.items():
            m2 = re.match(r"reader\|(.+)$", k)
            if m2 and isinstance(v, dict) and v.get("stop_at"):
                yield (os.path.basename(path), m2.group(1), "Chapter " + ch, v["stop_at"])


def g1_contradictions():
    paths = sorted(glob.glob(os.path.join(QA, "literary_runs", "2026*.json")))
    paths = [p for p in paths if not os.path.basename(p).startswith("patch_")]
    newest = paths[-1]
    d = json.load(open(newest))
    seen, out = set(), []
    for k, v in d.get("raw", {}).items():
        if not k.startswith("facts|"):
            continue
        for c in v.get("contradictions") or []:
            topic = c.get("fact", "")
            a, b = c.get("a", {}), c.get("b", {})
            key = (topic, a.get("quote"), b.get("quote"))
            if key in seen:
                continue
            seen.add(key)
            out.append({"topic": topic, "a": a, "b": b})
    return newest, out


def known_ids(topic, queue_lines):
    words = [w for w in re.findall(r"[a-z]{4,}", topic.lower())]
    hits = []
    for line in queue_lines:
        ll = line.lower()
        if sum(1 for w in words if w in ll) >= 2:
            m = re.match(r"\|\s*(B\d+)\s*\|", line)
            if m:
                hits.append(m.group(1))
    return hits


def main():
    queue_lines = open(QUEUE, encoding="utf-8").read().splitlines()

    stops = list(iter_reader_stops())
    themes = {}
    words = "One Two Three Four Five Six Seven Eight Nine Ten".split()
    for run, persona, ch, quote in stops:
        ch = str(ch).replace("Chapter ", "").strip()
        ch = words[int(ch) - 1] if ch.isdigit() and 0 < int(ch) <= 10 else ch
        t = classify(quote)
        themes.setdefault(t, []).append(
            {"run": run, "persona": persona, "chapter": ch, "quote": quote}
        )

    signals = []
    for t, rows in sorted(themes.items()):
        if t == "other" or len(rows) < 3:
            continue
        if len({r["chapter"] for r in rows}) >= 2 or len({r["persona"] for r in rows}) >= 2:
            signals.append((t, rows))

    newest, conds = g1_contradictions()
    known, new = [], []
    for c in conds:
        ids = known_ids(c["topic"], queue_lines)
        (known if ids else new).append((c, ids))

    lines = []
    lines.append("# Creator queue proposals (auto-generated by scripts/premise_router.py)")
    lines.append("")
    lines.append("Proposals only. Nothing here edits `duane_review_queue.md`; the creator")
    lines.append("decides what to adopt. Sources: `qa/literary_runs/2026*.json` (reader")
    lines.append("persona stops) and the newest run's G1 contradiction candidates.")
    lines.append("")
    lines.append("## A. Reader-stop theme clusters flagged as premise signals")
    lines.append("")
    lines.append("Rule: >= 3 stops of the same theme, spanning >= 2 chapters or >= 2 personas.")
    lines.append("")
    if signals:
        lines.append("| Theme | Stops | Chapters | Personas | Sample quotes (up to 3) |")
        lines.append("|---|---|---|---|---|")
        for t, rows in signals:
            chapters = ", ".join(sorted({r["chapter"] for r in rows}))
            personas = ", ".join(sorted({r["persona"] for r in rows}))
            samples = " · ".join(
                '"' + r["quote"][:90] + '" (' + r["chapter"] + ", " + r["persona"] + ")"
                for r in rows[:3]
            )
            lines.append(f"| {t} | {len(rows)} | {chapters} | {personas} | {samples} |")
    else:
        lines.append("(none)")
    lines.append("")
    lines.append("## B. NEW contradiction candidates (not matched to an existing queue row)")
    lines.append("")
    if new:
        for c, _ in new:
            lines.append(f"- **{c['topic']}**")
            lines.append(f"  - Version A (Ch {c['a'].get('chapter')}): \"{c['a'].get('quote')}\"")
            lines.append(f"  - Version B (Ch {c['b'].get('chapter')}): \"{c['b'].get('quote')}\"")
    else:
        lines.append("(none)")
    lines.append("")
    lines.append(f"## C. KNOWN contradictions (already in duane_review_queue.md; ids only)")
    lines.append("")
    lines.append(f"Source run: `{newest}`")
    for c, ids in known:
        lines.append(f"- {', '.join(ids)} — {c['topic']}")
    lines.append("")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT}: {len(stops)} stops, {len(signals)} premise signals, "
          f"{len(new)} NEW + {len(known)} KNOWN contradictions")


if __name__ == "__main__":
    main()
