-- Migration: 20261003000200_orders_refund_reversal.sql
-- Description: Widen public.orders event_type check to ('sale', 'refund', 'refund_reversal')
-- Rationale: P1 won chargeback dispute restores the sale via refund_reversal event.

-- Drop the inline check constraint generated by 20260927000200_orders_ledger.sql
alter table public.orders
  drop constraint if exists orders_event_type_check;

-- Re-add the check constraint with 'refund_reversal' included
alter table public.orders
  add constraint orders_event_type_check
  check (event_type in ('sale', 'refund', 'refund_reversal'));

-- Reload PostgREST schema cache
notify pgrst, 'reload schema';
